import type { ReceiptItem, ReceiptReview } from '@sackerl/api-client';

export function reviewItem(patch: Partial<ReceiptItem> = {}): ReceiptItem {
  return {
    id: 'line-1',
    receiptId: 'receipt-1',
    generationId: 'generation-1',
    householdId: 'home',
    clientLineId: null,
    source: 'parser',
    included: true,
    reviewState: 'unresolved',
    confidence: 0.99,
    confidenceLevel: 'high',
    rawText: 'MILCH 1L',
    lineIndex: 0,
    effectiveName: 'Milk',
    effectiveCategoryId: 'dairy',
    effectiveQtyUnit: 'l',
    effectiveQtyValue: 1,
    inferredName: 'MILCH',
    inferredCategoryId: 'dairy',
    inferredQtyUnit: 'l',
    inferredQtyValue: 1,
    inferredDiscountCents: null,
    inferredLineTotalCents: null,
    inferredTaxCents: null,
    inferredUnitPriceCents: null,
    correctedName: 'Milk',
    correctedCategoryId: null,
    correctedQtyUnit: null,
    correctedQtyValue: null,
    correctedAt: null,
    correctedBy: null,
    reviewedAt: null,
    reviewedBy: null,
    expiry: { date: null, state: 'unknown' },
    expiryChangedAt: null,
    expiryChangedBy: null,
    parserVersion: 'fixture',
    unresolvedFields: [],
    createdAt: '2026-09-28',
    updatedAt: '2026-09-28',
    ...patch,
  };
}

export function receiptReview(items: readonly ReceiptItem[] = [reviewItem()]): ReceiptReview {
  return {
    items,
    receipt: {
      id: 'receipt-1',
      householdId: 'home',
      activeParseGenerationId: 'generation-1',
      reviewRevision: 7,
      reviewStatus: 'needs_review',
      status: 'parsed',
      storeName: 'Test shop',
      purchasedOn: '2026-09-28',
      totalCents: 299,
      currency: 'EUR',
      imageUrl: 'sackerl://fixture',
      capturedAt: '2026-09-28',
      createdAt: '2026-09-28',
      updatedAt: '2026-09-28',
      parsedAt: '2026-09-28',
      reviewedAt: null,
      reviewedBy: null,
    },
    summary: {
      canComplete: false,
      generationId: 'generation-1',
      includedCount: items.length,
      receiptId: 'receipt-1',
      reviewRevision: 7,
      reviewStatus: 'needs_review',
      reviewedCount: 0,
      totalLines: items.length,
      unresolvedCount: items.length,
      unresolvedFields: [],
    },
  };
}
